### ISSUE TITLE
As an instructor, I want to have a screen to manage all my sections so that I can return to them and view them separately.

### ISSUE THREAD

**Issue by Brunswick-Khorasan** [snowminc/Groupformer#16] opened 2021-02-19 18:53 UTC
Having a section management system would make it much easier for the instructor to view ongoing response collections, finished response collections, etc. They could also name it for clarity as well.

**Comment by snowminc** [comment] 2021-04-19 22:54
Duplicate of #78

For the most part, the Results Screen already shows the instructor most of the details, plus a "Generate Groups" button.

**Closed by snowminc** 2021-04-19 22:54 UTC
Labels: duplicate, epic: Setup Screen, stretch goal
